buildscript {
	repositories {
		gradlePluginPortal()
	}
	dependencies {
		classpath 'org.xtext:xtext-gradle-plugin:4.0.0'
		classpath 'com.netflix.nebula:nebula-project-plugin:8.2.0'
		classpath "com.gradle.publish:plugin-publish-plugin:0.15.0"
	}
}

subprojects {
	apply plugin: 'java'
	java {
	    toolchain {
	        languageVersion.set(JavaLanguageVersion.of(11))
	    }
	}

	tasks.withType(JavaCompile) {
		options.encoding = 'UTF-8'
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		testImplementation 'junit:junit:4.13.2'
		testImplementation 'org.ow2.asm:asm:9.10.1'
	}
}
