buildscript {
	repositories {
		mavenLocal()
		gradlePluginPortal()
	}
	dependencies {
		classpath 'org.xtext:xtext-gradle-plugin:5.0.0-gradle9-SNAPSHOT'
		classpath "com.gradle.publish:plugin-publish-plugin:2.2.1"
	}
}

subprojects {
	apply plugin: 'java'
	java {
	    toolchain {
	        languageVersion.set(JavaLanguageVersion.of(17))
	    }
	}

	tasks.withType(JavaCompile) {
		options.encoding = 'UTF-8'
		options.release.set(17)
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		testImplementation 'junit:junit:4.13.2'
		testImplementation 'org.ow2.asm:asm:9.10.1'
		testImplementation gradleApi()
		testImplementation gradleTestKit()
	}
}
