description 'A plugin for invoking Xtext base Code generators'

apply plugin: 'org.xtext.xtend'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.gradle.plugin-publish'
apply plugin: 'maven-publish'

group = 'org.xtext'
version = findProperty('releaseVersion')

xtext {
	version.set(latestXtextVersion)
}

sourceSets {
	integTest {
		compileClasspath += sourceSets.main.output + sourceSets.test.output
		runtimeClasspath += sourceSets.main.output + sourceSets.test.output
	}
}

configurations {
	integTestImplementation.extendsFrom testImplementation
	integTestRuntimeOnly.extendsFrom testRuntimeOnly
	builder {
		transitive = false
	}
	protocol {
		transitive = false
	}
	compileClasspath {
		extendsFrom protocol
	}
	testImplementation {
		extendsFrom protocol
	}
}

dependencies {
	builder project(':xtext-gradle-builder')
	implementation "org.eclipse.xtend:org.eclipse.xtend.lib:$latestXtextVersion"
	implementation 'com.google.guava:guava:33.4.8-jre'
	implementation 'org.eclipse.platform:org.eclipse.equinox.preferences:3.10.200'
	implementation 'org.eclipse.platform:org.eclipse.equinox.common:3.18.0'
	implementation 'org.osgi:org.osgi.framework:1.10.0'
	implementation 'org.osgi:org.osgi.service.prefs:1.1.2'
	implementation('org.apache.maven:maven-artifact:3.9.16') {
		transitive = false
	}
	protocol project(':xtext-gradle-protocol')
	testImplementation 'org.ow2.asm:asm:9.10.1'
}

gradlePlugin {
	website = 'https://www.eclipse.org/Xtext/'
	vcsUrl = 'https://github.com/xtext/xtext-gradle-plugin'
	plugins {
		xtext {
			id = "org.xtext.builder"
			displayName = "Xtext Gradle Plugin"
			description = "A Gradle plugin for generating code with Xtext"
			implementationClass = "org.xtext.gradle.XtextBuilderPlugin"
			tags = ['Xtext', 'Xtend', 'DSL']
		}
		xtend {
			id = "org.xtext.xtend"
			displayName = "Xtend Gradle Plugin"
			description = "A Gradle plugin for the Xtend language"
			implementationClass = "org.xtext.gradle.XtendLanguagePlugin"
			tags = ['Xtext', 'Xtend', 'DSL']
		}
	}
	testSourceSets sourceSets.integTest
}

javadoc.dependsOn generateXtext

processResources {
	inputs.files(configurations.protocol)
	from(configurations.builder) {
		rename {
			"xtext-gradle-builder.jar"
		}
	}
	from({zipTree(configurations.protocol.singleFile)})
}

tasks.withType(Test) {
	def testkitDir = System.getenv("CI") ? gradle.gradleUserHomeDir : "$rootDir/testkit-dir"
	systemProperty 'gradle.project.version', version
	systemProperty 'org.gradle.testkit.dir', testkitDir
}

def minimumIntegrationTest = tasks.register('minimumIntegrationTest', Test) {
	group = 'verification'
	testClassesDirs = sourceSets.integTest.output.classesDirs
	classpath = sourceSets.integTest.runtimeClasspath
	reports.html.outputLocation.set(layout.buildDirectory.dir("reports/tests/$name"))
	reports.junitXml.outputLocation.set(layout.buildDirectory.dir("test-results/$name"))
	systemProperty 'gradle.version', minimumGradleVersion
	systemProperty 'xtext.version', minimumXtextVersion
	def minTestJavaHome = findProperty('minTestJavaHome')
	if (minTestJavaHome != null) {
		systemProperty 'org.xtext.gradle.test.javaHome', minTestJavaHome
	}
}

def latestIntegrationTest = tasks.register('latestIntegrationTest', Test) {
	group = 'verification'
	classpath = minimumIntegrationTest.get().classpath
	testClassesDirs = minimumIntegrationTest.get().testClassesDirs
	systemProperty 'gradle.version', latestGradleVersion
	systemProperty 'xtext.version', latestXtextVersion
	javaLauncher.set(javaToolchains.launcherFor {
		languageVersion.set(JavaLanguageVersion.of(17))
	})
}

check.dependsOn(minimumIntegrationTest, latestIntegrationTest)
