description = 'A small wrapper for Xtext to make it easier to use from Gradle'

apply plugin: 'org.xtext.xtend'

xtext {
	version.set(latestXtextVersion)
}

dependencies {
	compileOnly project(':xtext-gradle-protocol')
	compileOnly gradleApi()
	compileOnly "org.eclipse.xtend:org.eclipse.xtend.lib:$latestXtextVersion"
	compileOnly "org.eclipse.xtext:org.eclipse.xtext:$latestXtextVersion"
	compileOnly "org.eclipse.xtext:org.eclipse.xtext.smap:$latestXtextVersion"
	compileOnly "org.eclipse.xtext:org.eclipse.xtext.xbase:$latestXtextVersion"
	compileOnly "org.eclipse.xtext:org.eclipse.xtext.java:$latestXtextVersion"
}
